### ISSUE TITLE
Trying different kinds of files

### ISSUE THREAD

**Issue by anirudt** [povilasb/docker-demo-quic-server#1]
Hi,

I wanted to test the setup with different kinds of data files, like video, images, etc. How do I go about doing that?

Thanks!

**Comment by povilasb** [comment]
I'm haven't tried that.
It depends on quic toy server: https://www.chromium.org/quic/playing-with-quic
Try to ask someone if quic toy server supports such functionality:  https://groups.google.com/a/chromium.org/forum/#!forum/proto-quic

If it does, I could update the docker image.

**Comment by anirudt** [comment]
Thanks for the Google group link, I have posted there. Let's wait for their response.
